# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0004_participants_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='phoneNumber',
            field=models.TextField(verbose_name='phone number'),
        ),
    ]
