# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0005_auto_20190711_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user is admin site.', verbose_name='admin status'),
        ),
    ]
