# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0007_participants_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='gender',
            field=models.TextField(blank=True, help_text='Gender of the Participant', null=True, verbose_name='gender'),
        ),
    ]
