# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0008_participants_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='fee_status',
            field=models.TextField(blank=True, help_text='Fee status of the Participant', null=True, verbose_name='fee status'),
        ),
    ]
