# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0010_participants_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='responsible_person',
            field=models.TextField(blank=True, help_text='Responsible Person of the Participant', null=True, verbose_name='responsible person'),
        ),
        migrations.AddField(
            model_name='participants',
            name='responsible_person_contact',
            field=models.TextField(blank=True, help_text='Contact of the Responsible Person of the Participant', null=True, verbose_name='responsible person contact'),
        ),
    ]
