# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0012_auto_20190809_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='is_participant',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='participants',
            name='is_volunteer',
            field=models.BooleanField(),
        ),
    ]
